### PR TITLE
kyber/dilithium aarch64 pull from pqclean + patches

### LINKED ISSUE #1506: macOS M1: dilithium/aarch64 not compiling with gcc
**Describe the bug**
Compiling fails on macOS (M1) when using gcc.

```
...
[ 63%] Building ASM object src/sig/dilithium/CMakeFiles/dilithium_2_aarch64.dir/pqclean_dilithium2_aarch64/__asm_iNTT.S.o
/Users/bhe/git/liboqs/src/sig/dilithium/pqclean_dilithium2_aarch64/__asm_iNTT.S:8:1: error: unknown directive
.type PQCLEAN_DILITHIUM2_AARCH64_asm_intt_SIMD_top, %function
^
/Users/bhe/git/liboqs/src/sig/dilithium/pqclean_dilithium2_aarch64/__asm_iNTT.S:418:1: error: unknown directive
.type PQCLEAN_DILITHIUM2_AARCH64_asm_intt_SIMD_bot, %function
^
...
```

**To Reproduce**
```
cmake -DCMAKE_C_COMPILER=gcc-13 ..
make
```

**Environment (please complete the following information):**
 - OS: macOS 13.4.1
 - OpenSSL version 1.1.1t
 - Compiler version used: gcc-13 (Homebrew GCC 13.1.0) 13.1.0
 - Build variables used "-DCMAKE_C_COMPILER=gcc-13"
 - liboqs version: main

**Additional context**
The respective ".type <fun>, %function" statements in the aarch64 assembly code are excluded for clang but not for gcc:
https://github.com/open-quantum-safe/liboqs/blob/93e784725e3be0aaa2691a557456ff786155a7b2/src/sig/dilithium/pqclean_dilithium2_aarch64/__asm_iNTT.S#L7-L9
PQClean upstream appears to have removed the ".type <fun>, %function" statements in the [meanwhile](https://github.com/PQClean/PQClean/commit/0b8db0f8323734b60f638c97f026ac8b66b42378), so a fresh copy_from_upstream might help.

### PR DESCRIPTION
**Pull request by bhess**
- Runs copy_from_upstream with pqclean code, updating kyber and dilithium for aarch64
- Updates upstream patches & adds a few more fixes 
- Fixes a compiler warning in the arm aes code (https://github.com/open-quantum-safe/liboqs/issues/1506#issuecomment-1641645941)
- Fixes #1506 #1320
- Updates a few pqclean upstream licenses. 
- adds a falcon update from pqclean upstream
- updated dilithium suppression files (changed line numbers) -> CT tests passing using Fedora/aarch64

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [ ] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

TODOs: 

- [x] KATs of 2 out of 3 Kyber versions (768, 1024) seem to fail with the updated upstream code.
@Martyrshot did you face any similar issues when including the previous code?
- [x] Update license infos

### CODE REVIEW

**Comment by mczraf** [comment]
@bhess Thank you for working on the KAT mismatch issue. Quick question: would you have any rough time estimate for the integration of this pull-request? I suspect that the KAT mismatch needs to be fixed first but is there any other blocking issues for this integration?

File: src/kem/kyber/pqclean_kyber1024_aarch64/NTT_params.h [hunk 1]
```diff
@@ -1,3 +1,30 @@
+
+/*
+ * CC0 1.0 Universal or the following MIT License
+ *
+ * MIT License
```
Comment (baentsch) [inline src/kem/kyber/pqclean_kyber1024_aarch64/NTT_params.h:5]: This (dual license) is good(ness) in light of #1437. But then the contents of the PQClean aarch upstream algorithm YML seem to need updating (to also list MIT), no?

File: src/kem/kyber/pqclean_kyber1024_aarch64/fips202x2.h [hunk 2]
```diff
@@ -1,10 +1,17 @@
+
+/*
+ * This file is licensed
+ * under Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0.html)
```
Comment (baentsch) [inline src/kem/kyber/pqclean_kyber1024_aarch64/fips202x2.h:4]: Another license for the YML...

File: src/kem/kyber/pqclean_kyber1024_aarch64/feat.S [hunk 3]
```diff
@@ -0,0 +1,168 @@
+
+/*
+MIT License
```
Comment (bhess) [inline src/kem/kyber/pqclean_kyber1024_aarch64/feat.S:3]: This is MIT only

File: src/kem/kyber/pqclean_kyber1024_aarch64/__asm_poly.S [hunk 4]
```diff
@@ -1,14 +1,37 @@
 
+/*
+ * CC0 1.0 Universal or the following MIT License
```
Comment (bhess) [inline src/kem/kyber/pqclean_kyber1024_aarch64/__asm_poly.S:3]: CC0 or MIT

File: src/kem/kyber/pqclean_kyber1024_aarch64/fips202x2.h (hunk 2 above)
Comment (bhess) [reply src/kem/kyber/pqclean_kyber1024_aarch64/fips202x2.h:4]: I read here Apache-2.0 or CC0 (for the SPDX-id)

**Comment by bhess** [comment]
KATs are now matching and the license infos updated, so the PR seems ready from my side @mczraf . The constant-time tests mentioned in https://github.com/open-quantum-safe/liboqs/issues/1320#issuecomment-1640641574 are now also passing (tested locally, there isn't a CI CT-run for arm at the moment).

The update appears to include the changes noted in https://github.com/open-quantum-safe/liboqs/issues/1245#issuecomment-1319218926 (i.e. feat.s), so it should close #1320.

@dstebila There's a small Falcon update as part in this pqclean-pull you wanted to check if it is ok to include.

**Comment by baentsch** [comment]
LGTM. Thanks!

File: src/kem/kyber/pqclean_kyber1024_aarch64/Makefile
Comment (dstebila) [inline src/kem/kyber/pqclean_kyber1024_aarch64/Makefile:1]: We should be able to delete this file, the PQClean Makefiles are not needed nor used in liboqs.

**Review by dstebila — APPROVED** [review]

File: src/kem/kyber/pqclean_kyber1024_aarch64/Makefile
Comment (dstebila) [reply src/kem/kyber/pqclean_kyber1024_aarch64/Makefile:1]: As well as the other Makefiles in the PQClean directories.

**Review by dstebila — CHANGES_REQUESTED** [review]
Please remove superfluous Makefiles

File: src/kem/kyber/pqclean_kyber1024_aarch64/Makefile
Comment (bhess) [reply src/kem/kyber/pqclean_kyber1024_aarch64/Makefile:1]: Added a commit that removes them.

**Comment by bhess** [comment]
> Please remove superfluous Makefiles

The makefiles are removed now, updated the copy_from_upstream script to handle this case when there are arch-specific upstreams.

**Review by dstebila — APPROVED** [review]

File: docs/algorithms/kem/kyber.yml [hunk 5]
```diff
@@ -22,9 +22,9 @@ primary-upstream:
   spdx-license-identifier: CC0-1.0 or Apache-2.0
 optimized-upstreams:
   pqclean-aarch64:
-    source: https://github.com/PQClean/PQClean/commit/d742438e5c541958bfd58070cd8668d757d88e07
+    source: https://github.com/PQClean/PQClean/commit/66e50172055aaf1b9a16d8f35fe03b0807f2723e
       with copy_from_upstream patches
-    spdx-license-identifier: CC0-1.0
+    spdx-license-identifier: (CC0-1.0 or Apache-2.0) and (CC0-1.0 or MIT) and MIT
```
Comment (baentsch) [inline docs/algorithms/kem/kyber.yml:27]: A question regarding this SPDX documentation: Am I assuming right that this has been manually created from the single source code LICENSE files? In addition, is it intentional (and legal) to not include the actual LICENSE file(s) from PQClean? When looking at the contents of those (example: https://github.com/PQClean/PQClean/blob/master/crypto_kem/kyber1024/aarch64/LICENSE) the documented upstream license does not seem to be in line with the SPDX statement in this PR -- or am I overlooking where Apache-2.0 is granted for the whole of the `aarch64` kyber code base? Or did https://github.com/PQClean/PQClean/pull/488 simply fail to update the main LICENSE file?

File: docs/algorithms/sig/sphincs.yml [hunk 6]
```diff
@@ -26,7 +26,7 @@ nist-round: 3
 spec-version: NIST Round 3 submission, v3.1 (June 10, 2022)
 spdx-license-identifier: CC0-1.0
 primary-upstream:
-  source: https://github.com/PQClean/PQClean/commit/d742438e5c541958bfd58070cd8668d757d88e07
+  source: https://github.com/PQClean/PQClean/commit/66e50172055aaf1b9a16d8f35fe03b0807f2723e
```
Comment (baentsch) [inline docs/algorithms/sig/sphincs.yml:29]: Similar (license documentation) question here: This states CC0 -- which is textually correct looking at the immediate [LICENSE upstream in PQClean](https://github.com/PQClean/PQClean/blob/master/crypto_sign/sphincs-sha2-256s-robust/clean/LICENSE). When looking at the ultimate origin code base [Sphincs+ is multi licensed](https://github.com/sphincs/sphincsplus/blob/master/LICENSE). If we manually "curate" license statements (see comment on kyber above) why not do the same with Sphincs+? This would resolve #1437 without having to push LICENSE statements "through" PQClean.

File: docs/algorithms/kem/kyber.yml (hunk 5 above)
Comment (bhess) [reply docs/algorithms/kem/kyber.yml:27]: The spdx-license-identifier was manually curated looking at the license information in the headers of the individual files. It would be nicer if there was a single LICENSE or NOTICE file upstream containing all this information. The main LICENSE indeed seems out of sync, I don't know if this is intentional. @dstebila, since you reviewed https://github.com/PQClean/PQClean/pull/488, do you have an insight here?

File: docs/algorithms/sig/sphincs.yml (hunk 6 above)
Comment (bhess) [reply docs/algorithms/sig/sphincs.yml:29]: Not sure if this is possible if PQClean only lists CC0.

Comment (baentsch) [reply docs/algorithms/sig/sphincs.yml:29]: In that case [manual curation](https://github.com/open-quantum-safe/liboqs/pull/1512#discussion_r1271902542) in general should stop and we ought to move to full automation (see #1514).

Comment (bhess) [reply docs/algorithms/sig/sphincs.yml:29]: Agreed. However, there seems to be a nuance when curating the information (no matter if manual or automatic):
(1) Kyber/aarch64 case: PQClean LICENSE file lists one license and the PQClean source files contain more/other licenses.
(2) SPHNCS+ case: PQClean code base lists a single license. The code's ancestor contains more/other licenses.

Comment (baentsch) [reply docs/algorithms/sig/sphincs.yml:29]: "Manual" curation allows (arguably/hopefully legally informed) updates, automated license collection does not. In either case, work is required (whether already in this PR or only when/if resolving #1514, I leave to the reviewers of this PR).

File: docs/algorithms/kem/kyber.yml (hunk 5 above)
Comment (dstebila) [reply docs/algorithms/kem/kyber.yml:27]: No insight; the PR only modified the individual files, rather than touching the related licence file.  Probably an oversight.

File: docs/algorithms/sig/dilithium.md [hunk 7]
```diff
@@ -12,7 +12,7 @@
 - **Optimized Implementation sources**: https://github.com/pq-crystals/dilithium/commit/3e9b9f1412f6c7435dbeb4e10692ea58f181ee51 with copy_from_upstream patches
   - **pqclean-aarch64**:<a name="pqclean-aarch64"></a>
       - **Source**: https://github.com/PQClean/PQClean/commit/66e50172055aaf1b9a16d8f35fe03b0807f2723e with copy_from_upstream patches
-      - **Implementation license (SPDX-Identifier)**: (CC0-1.0 or Apache-2.0) and (CC0-1.0 or MIT) and MIT
+      - **Implementation license (SPDX-Identifier)**: CC0-1.0 and (CC0-1.0 or Apache-2.0) and (CC0-1.0 or MIT) and MIT
```
Comment (baentsch) [inline docs/algorithms/sig/dilithium.md:15]: Do I understand this logical statement to now mean that CC0 applies for PQClean code for Dilithium `aarch64` (as well as --the commercially less problematic-- MIT license)? In other words, from the perspective of #1437 an automated license check permitting only MIT and Apache code now has to exclude Dilithium `aarch64` code (which was not the case before this commit), right?

Comment (bhess) [reply docs/algorithms/sig/dilithium.md:15]: I'd personally agree with this interpretation, but tagging @beldmit for his feedback.
The CC0 was added in the commit because the main LICENSE file mentions only CC0, I've added an issue upstream to clarify if this is an oversight or intentional: https://github.com/PQClean/PQClean/issues/495.

**Review by dstebila — APPROVED** [review]
