### PR TITLE
Fixing OpenSSL SHA2 incremental API integration

### LINKED ISSUE #1452: Bug in OSX integration of OpenSSL
**Describe the bug**
On a newly-prepared platform , I'm getting a ton of errors trying to run test-suite:
```text
.  .  .
tests/test_speed.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

command = ['/Users/ur20980/src/liboqs/build/tests/speed_sig', 'SPHINCS+-SHAKE256-256s-robust', '-f']
working_dir = '.'
env = {'ANT_OPTS': '-Dhttp.proxyHost=llproxy.llan.ll.mit.edu -Dhttp.proxyPort=8080', 'AS': 'yasm -m amd64 -f macho64 -p gas -X gnu ', 'AS_INTEGRATED_ASSEMBLER': '1', 'BASH_SILENCE_DEPRECATION_WARNING': '1', ...}
expected_returncode = 0, input = None, ignore_returncode = False

    def run_subprocess(command, working_dir='.', env=None, expected_returncode=0, input=None, ignore_returncode=False):
        """
        Helper function to run a shell command and report success/failure
        depending on the exit status of the shell command.
        """
        env_ = os.environ.copy()
        if env is not None:
            env_.update(env)
        env = env_
    
        # Note we need to capture stdout/stderr from the subprocess,
        # then print it, which pytest will then capture and
        # buffer appropriately
        print(working_dir + " > " + " ".join(command))
    
        result = subprocess.run(
                command,
                input=input,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                cwd=working_dir,
                env=env,
            )
    
        if not(ignore_returncode) and (result.returncode != expected_returncode):
            print(result.stdout.decode('utf-8'))
>           assert False, "Got unexpected return code {}".format(result.returncode)
E           AssertionError: Got unexpected return code -4

tests/helpers.py:42: AssertionError
-------------------------------------------- Captured stdout call --------------------------------------------
. > /Users/ur20980/src/liboqs/build/tests/speed_sig SPHINCS+-SHAKE256-256s-robust -f

__________________________________ test_sig[SPHINCS+-SHAKE256-256f-simple] ___________________________________
[gw11] darwin -- Python 3.11.3 /opt/local/bin/python3

sig_name = 'SPHINCS+-SHAKE256-256f-simple'

    @helpers.filtered_test
    @pytest.mark.parametrize('sig_name', helpers.available_sigs_by_name())
    def test_sig(sig_name):
        kats = helpers.get_kats("sig")
        if not(helpers.is_sig_enabled_by_name(sig_name)): pytest.skip('Not enabled')
>       helpers.run_subprocess( [helpers.path_to_executable('speed_sig'), sig_name, "-f"])

tests/test_speed.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

command = ['/Users/ur20980/src/liboqs/build/tests/speed_sig', 'SPHINCS+-SHAKE256-256f-simple', '-f']
working_dir = '.'
env = {'ANT_OPTS': '-Dhttp.proxyHost=llproxy.llan.ll.mit.edu -Dhttp.proxyPort=8080', 'AS': 'yasm -m amd64 -f macho64 -p gas -X gnu ', 'AS_INTEGRATED_ASSEMBLER': '1', 'BASH_SILENCE_DEPRECATION_WARNING': '1', ...}
expected_returncode = 0, input = None, ignore_returncode = False

    def run_subprocess(command, working_dir='.', env=None, expected_returncode=0, input=None, ignore_returncode=False):
        """
        Helper function to run a shell command and report success/failure
        depending on the exit status of the shell command.
        """
        env_ = os.environ.copy()
        if env is not None:
            env_.update(env)
        env = env_
    
        # Note we need to capture stdout/stderr from the subprocess,
        # then print it, which pytest will then capture and
        # buffer appropriately
        print(working_dir + " > " + " ".join(command))
    
        result = subprocess.run(
                command,
                input=input,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                cwd=working_dir,
                env=env,
            )
    
        if not(ignore_returncode) and (result.returncode != expected_returncode):
            print(result.stdout.decode('utf-8'))
>           assert False, "Got unexpected return code {}".format(result.returncode)
E           AssertionError: Got unexpected return code -4

tests/helpers.py:42: AssertionError
-------------------------------------------- Captured stdout call --------------------------------------------
. > /Users/ur20980/src/liboqs/build/tests/speed_sig SPHINCS+-SHAKE256-256f-simple -f

__________________________________ test_sig[SPHINCS+-SHAKE256-192f-robust] ___________________________________
[gw4] darwin -- Python 3.11.3 /opt/local/bin/python3

sig_name = 'SPHINCS+-SHAKE256-192f-robust'

    @helpers.filtered_test
    @pytest.mark.parametrize('sig_name', helpers.available_sigs_by_name())
    def test_sig(sig_name):
        kats = helpers.get_kats("sig")
        if not(helpers.is_sig_enabled_by_name(sig_name)): pytest.skip('Not enabled')
>       helpers.run_subprocess( [helpers.path_to_executable('speed_sig'), sig_name, "-f"])

tests/test_speed.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

command = ['/Users/ur20980/src/liboqs/build/tests/speed_sig', 'SPHINCS+-SHAKE256-192f-robust', '-f']
working_dir = '.'
env = {'ANT_OPTS': '-Dhttp.proxyHost=llproxy.llan.ll.mit.edu -Dhttp.proxyPort=8080', 'AS': 'yasm -m amd64 -f macho64 -p gas -X gnu ', 'AS_INTEGRATED_ASSEMBLER': '1', 'BASH_SILENCE_DEPRECATION_WARNING': '1', ...}
expected_returncode = 0, input = None, ignore_returncode = False

    def run_subprocess(command, working_dir='.', env=None, expected_returncode=0, input=None, ignore_returncode=False):
        """
        Helper function to run a shell command and report success/failure
        depending on the exit status of the shell command.
        """
        env_ = os.environ.copy()
        if env is not None:
            env_.update(env)
        env = env_
    
        # Note we need to capture stdout/stderr from the subprocess,
        # then print it, which pytest will then capture and
        # buffer appropriately
        print(working_dir + " > " + " ".join(command))
    
        result = subprocess.run(
                command,
                input=input,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                cwd=working_dir,
                env=env,
            )
    
        if not(ignore_returncode) and (result.returncode != expected_returncode):
            print(result.stdout.decode('utf-8'))
>           assert False, "Got unexpected return code {}".format(result.returncode)
E           AssertionError: Got unexpected return code -4

tests/helpers.py:42: AssertionError
-------------------------------------------- Captured stdout call --------------------------------------------
. > /Users/ur20980/src/liboqs/build/tests/speed_sig SPHINCS+-SHAKE256-192f-robust -f

__________________________________ test_sig[SPHINCS+-SHAKE256-256s-simple] ___________________________________
[gw2] darwin -- Python 3.11.3 /opt/local/bin/python3

sig_name = 'SPHINCS+-SHAKE256-256s-simple'

    @helpers.filtered_test
    @pytest.mark.parametrize('sig_name', helpers.available_sigs_by_name())
    def test_sig(sig_name):
        kats = helpers.get_kats("sig")
        if not(helpers.is_sig_enabled_by_name(sig_name)): pytest.skip('Not enabled')
>       helpers.run_subprocess( [helpers.path_to_executable('speed_sig'), sig_name, "-f"])

tests/test_speed.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

command = ['/Users/ur20980/src/liboqs/build/tests/speed_sig', 'SPHINCS+-SHAKE256-256s-simple', '-f']
working_dir = '.'
env = {'ANT_OPTS': '-Dhttp.proxyHost=llproxy.llan.ll.mit.edu -Dhttp.proxyPort=8080', 'AS': 'yasm -m amd64 -f macho64 -p gas -X gnu ', 'AS_INTEGRATED_ASSEMBLER': '1', 'BASH_SILENCE_DEPRECATION_WARNING': '1', ...}
expected_returncode = 0, input = None, ignore_returncode = False

    def run_subprocess(command, working_dir='.', env=None, expected_returncode=0, input=None, ignore_returncode=False):
        """
        Helper function to run a shell command and report success/failure
        depending on the exit status of the shell command.
        """
        env_ = os.environ.copy()
        if env is not None:
            env_.update(env)
        env = env_
    
        # Note we need to capture stdout/stderr from the subprocess,
        # then print it, which pytest will then capture and
        # buffer appropriately
        print(working_dir + " > " + " ".join(command))
    
        result = subprocess.run(
                command,
                input=input,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                cwd=working_dir,
                env=env,
            )
    
        if not(ignore_returncode) and (result.returncode != expected_returncode):
            print(result.stdout.decode('utf-8'))
>           assert False, "Got unexpected return code {}".format(result.returncode)
E           AssertionError: Got unexpected return code -4

tests/helpers.py:42: AssertionError
-------------------------------------------- Captured stdout call --------------------------------------------
. > /Users/ur20980/src/liboqs/build/tests/speed_sig SPHINCS+-SHAKE256-256s-simple -f

___________________________________ test_sig[SPHINCS+-SHA256-128f-robust] ____________________________________
[gw9] darwin -- Python 3.11.3 /opt/local/bin/python3

sig_name = 'SPHINCS+-SHA256-128f-robust'

    @helpers.filtered_test
    @pytest.mark.parametrize('sig_name', helpers.available_sigs_by_name())
    def test_sig(sig_name):
        kats = helpers.get_kats("sig")
        if not(helpers.is_sig_enabled_by_name(sig_name)): pytest.skip('Not enabled')
>       output = helpers.run_subprocess(
            [helpers.path_to_executable('kat_sig'), sig_name],
        )

tests/test_kat.py:29: 
.  .  .
```

**To Reproduce**
1. Clone, build optimized version, as per README.
2. Go to `build` subdirectory.
3. `ninja run_tests`

**Expected behavior**
Tests passing or being skipped, test-scripts not crashing.

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS Ventura 13.3.1 (a)
 - OpenSSL version: 3.2.0-dev
 - Compiler version used: Apple Clang 
 - Build variables used:
 ```
OPT="-DOQS_DIST_BUILD=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release"
env RUN_TESTS_PARALLEL_UPPER=FALSE cmake -GNinja .. -DOQS_USE_OPENSSL=ON ${OPT} -DCMAKE_INSTALL_PREFIX="${HOME}/openssl-3"
```
 - liboqs version: current main

**Additional context**
I hope you can point me at where/what in Python environment seems missing - maybe an older version of some module, or such...?

### PR DESCRIPTION
**Pull request by baentsch**
Possibly fixes #1452. Fixes issues in #1420.

- Corrects SHA2 API documentation
- Checks all SHA2 OpenSSL API return values
- Fixes SHA384 and SHA512 incremental API implementations
- Corrects testing for these APIs
- Enhances test vectors to avoid re-occurrence of problem

* [yes] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [no] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

### CODE REVIEW

**Comment by beldmit** [comment]
As we prefetch objects, it's probably worth exiting in case on initialization failure?

**Comment by baentsch** [comment]
> In theory, the problem is we need only some openssl-provided implementations for a particular application. So lack of SHA3 hashes shouldn't stop using SHA2.

Agreed. Is anything in this PR precluding this?

**Comment by baentsch** [comment]
> then it becomes a mess from a certification point of view

 Let's cross that bridge as and if we reach it.

File: src/common/common.h [hunk 1]
```diff
@@ -23,10 +24,12 @@ extern "C" {
  * Macro for terminating the program if x is
  * a null pointer.
  */
-#define OQS_EXIT_IF_NULLPTR(x)  \
-    do {                        \
-        if ( (x) == (void*)0 )  \
+#define OQS_EXIT_IF_NULLPTR(x)    \
```
Comment (xvzcf) [inline src/common/common.h:27]: Since the `fprintf` error message is OpenSSL specific, could you rename (or move) this to something like `OQS_EXIT_IF_OPENSSL_NULLPTR` or some such?

File: tests/test_hash.c [hunk 2]
```diff
@@ -176,9 +176,9 @@ static int do_sha512(void) {
 		return -2;
 	}
 	// hash with second state
-	if (msg_len > 64) {
+	if (msg_len > 128) {
```
Comment (xvzcf) [inline tests/test_hash.c:179]: Would it be possible to use the `#define`d constants here? That way we'd be testing the definitions we have in the code.

**Review by xvzcf — CHANGES_REQUESTED** [review]

File: src/common/sha2/sha2_ossl.c [hunk 3]
```diff
@@ -50,20 +54,21 @@ void OQS_SHA2_sha256_inc_init(OQS_SHA2_sha256_ctx *state) {
...
 
 void OQS_SHA2_sha256_inc_finalize(uint8_t *out, OQS_SHA2_sha256_ctx *state, const uint8_t *in, size_t inlen) {
 	unsigned int md_len;
 	if (inlen > 0) {
-		EVP_DigestUpdate((EVP_MD_CTX *) state->ctx, in, inlen);
+		OQS_OPENSSL_GUARD(EVP_DigestUpdate((EVP_MD_CTX *) state->ctx, in, inlen));
 	}
-	EVP_DigestFinal_ex((EVP_MD_CTX *) state->ctx, out, &md_len);
+	OQS_OPENSSL_GUARD(EVP_DigestFinal_ex((EVP_MD_CTX *) state->ctx, out, &md_len));
 	EVP_MD_CTX_free((EVP_MD_CTX *) state->ctx);
```
Comment (dstebila) [inline src/common/sha2/sha2_ossl.c:72]: Would there be any value in setting `state->ctx = NULL` after this as a precaution against double frees?

File: tests/test_hash.py [hunk 4]
```diff
@@ -50,7 +50,7 @@ def test_sha384(msg):
     assert(output.rstrip() == hashlib.sha384(msg.encode()).hexdigest())
 
 @helpers.filtered_test
-@pytest.mark.parametrize('msg', ['', 'a', 'abc', '1234567890123456789012345678901678901567890'])
+@pytest.mark.parametrize('msg', ['', 'a', 'abc', '1234567890123456789012345678901678901567890', '1234567890123456789012345678901678901567890andthensometohavemorethan64bytes', '1234567890123456789012345678901678901567890andlotsmoretexttosurelyandwithoutdoubtgobeyondthe128bytesrequiredtotriggerallincrementalblocklogiccases'])
```
Comment (dstebila) [inline tests/test_hash.py:53]: Were you able to confirm that these tests indeed fail with the old code?

File: src/common/sha2/sha2_ossl.c [hunk 5]
```diff
@@ -114,20 +120,21 @@ void OQS_SHA2_sha512_inc_init(OQS_SHA2_sha512_ctx *state) {
...
 	mdctx = EVP_MD_CTX_new();
-	EVP_DigestInit_ex(mdctx, md, NULL);
+	OQS_EXIT_IF_NULLPTR(mdctx);
+	OQS_OPENSSL_GUARD(EVP_DigestInit_ex(mdctx, md, NULL));
 	state->ctx = mdctx;
 }
 
 void OQS_SHA2_sha512_inc_blocks(OQS_SHA2_sha512_ctx *state, const uint8_t *in, size_t inblocks) {
-	EVP_DigestUpdate((EVP_MD_CTX *) state->ctx, in, inblocks * SHA2_BLOCK_SIZE);
+	OQS_OPENSSL_GUARD(EVP_DigestUpdate((EVP_MD_CTX *) state->ctx, in, inblocks * 2 * SHA2_BLOCK_SIZE));
```
Comment (dstebila) [inline src/common/sha2/sha2_ossl.c:129]: We'll have to revert f57ed6db90b4886a95e8cd5a885bc2660bbdf134 on #1420 but that's fine.

**Review by dstebila — APPROVED** [review]

File: tests/test_hash.py (hunk 4 above)
Comment (baentsch) [reply tests/test_hash.py:53]: > Were you able to confirm that these tests indeed fail with the old code?

Yes

File: tests/test_hash.c (hunk 2 above)
Comment (baentsch) [reply tests/test_hash.c:179]: > Would it be possible to use the `#define`d constants here? That way we'd be testing the definitions we have in the code.

I'd been looking for suitable define's as the old code also didn't have any. Which ones do you have in mind?

File: src/common/common.h (hunk 1 above)
Comment (baentsch) [reply src/common/common.h:27]: No code other than the _ossl files use this macro. But fine, I'll change this.

File: tests/test_hash.c (hunk 2 above)
Comment (dstebila) [reply tests/test_hash.c:179]: I don't think there are any constants exposed from the header files into this context. In which case I don't think it's worth the effort to add constants to expose just for this purpose.

File: tests/test_hash.c [hunk 6]
```diff
@@ -117,9 +117,9 @@ static int do_sha384(void) {
 	OQS_SHA2_sha384_ctx state2;
 	OQS_SHA2_sha384_inc_ctx_clone(&state2, &state);
 	// hash with first state
-	if (msg_len > 64) {
```
[the remark this answers is not in the document]
Comment (dstebila) [reply tests/test_hash.c:120]: Let's keep it as `test_hash.c`; in principal one could add other hash algorithms to it.  And in some sense, it does behave differently than `test_aes.c` and `test_sha3.c`: the AES and SHA-3 ones test against internal specified test vectors, where as `test_hash.c` just computes the hash of the supplied input which needs to be externally checked against another implementation or test vector.

File: src/common/sha2/sha2_ossl.c (hunk 3 above)
Comment (baentsch) [reply src/common/sha2/sha2_ossl.c:72]: so changed in https://github.com/open-quantum-safe/liboqs/pull/1454/commits/5f8d02c9c2651b9a5f3eca0364457a5b271a473a

File: tests/test_hash.c (hunk 2 above)
Comment (baentsch) [reply tests/test_hash.c:179]: As per Douglas' comment above, left unchanged in https://github.com/open-quantum-safe/liboqs/pull/1454/commits/5f8d02c9c2651b9a5f3eca0364457a5b271a473a

File: tests/test_hash.c (hunk 6 above)
[the remark this answers is not in the document]
Comment (baentsch) [reply tests/test_hash.c:120]: As per Douglas' comment above, left unchanged in https://github.com/open-quantum-safe/liboqs/pull/1454/commits/5f8d02c9c2651b9a5f3eca0364457a5b271a473a

File: src/common/common.h (hunk 1 above)
Comment (baentsch) [reply src/common/common.h]: Changed macro to always state where the problem occurs in https://github.com/open-quantum-safe/liboqs/pull/1454/commits/5f8d02c9c2651b9a5f3eca0364457a5b271a473a. 

I'd suggest looking into improving this in the future: What was the rationale for all these `void` functions? Maybe someone would like to raise an issue documenting what this is about and how it could be improved (at least stating more specifically what/where a problem occurred, if it occurred, such that users of `liboqs` have a better idea where to look for possible program termination causes).

Comment (dstebila) [reply src/common/common.h]: I think one reason for all these void functions is that the implementers of all the various PQ implementations we're using were working with SHA/AES APIs that didn't have return values -- they were assumed to just always work.  It would be very intrusive to go back to all of those calls deeply in the source code and change them all to have error handling.  We shouldn't forget about this if and when we start on the APIs for some of the other projects on the production track in the Foundation.

**Comment by dstebila** [comment]
I'm okay to merge this.

File: src/common/common.h (hunk 1 above)
Comment (xvzcf) [reply src/common/common.h]: > Changed macro to always state where the problem occurs in [5f8d02c](https://github.com/open-quantum-safe/liboqs/commit/5f8d02c9c2651b9a5f3eca0364457a5b271a473a).

I think using `__LINE__` and `__FILE__` macros would've been better to pinpoint the source of the error, but I won't hold up the merge for this since it's not specific to this PR.

Comment (baentsch) [reply src/common/common.h]: > I think using `__LINE__` and `__FILE__` macros would've been better to pinpoint the source of the error, but I won't hold up the merge for this since it's not specific to this PR.

Thanks -- this is a good idea. Silly me to not have thought about that earlier. But whatever, I'd vote for merging this now to make headway on #1420. We still have to properly address the old comment https://github.com/open-quantum-safe/liboqs/blob/9f912c957bfe7f4b894aa9661168a310e8dd1a58/src/common/common.h#L40

**Review by xvzcf — APPROVED** [review]
