### PR TITLE
correct free in test_kem/sig

### LINKED ISSUE #1398: Cleanup in test_sig.c seems wrong
The cleanup section in `tests/test_sig.c` has a check if `sig != NULL`, in which case it will free the `secret_key` buffer. But a bunch of other buffers are also only `malloc`d after `sig` is initialized.  This would not be a problem, because `OQS_MEM_insecure_free` handles `NULL` correctly, however, `sizeof(magic_t)` is subtracted from each of these pointers.

This should probably be handled differently; just moving the checks into the `sig != NULL` if is probably not sufficient as there is another case where they may end up there with some buffers partially initialized; if one of the `malloc`s fails.

### PR DESCRIPTION
**Pull request by baentsch**
Fixes #1398 

* [no] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

### CODE REVIEW

File: tests/test_kem.c [hunk 1]
```diff
@@ -163,12 +163,22 @@ static OQS_STATUS kem_test_correctness(const char *method_name) {
...
+		if (secret_key) {
+			OQS_MEM_secure_free(secret_key - sizeof(magic_t), kem->length_secret_key + 2 * sizeof(magic_t));
+		}
+		if (shared_secret_e) {
+			OQS_MEM_secure_free(shared_secret_e - sizeof(magic_t), kem->length_shared_secret + 2 * sizeof(magic_t));
+		}
+		if (shared_secret_d) {
+			OQS_MEM_secure_free(shared_secret_d - sizeof(magic_t), kem->length_shared_secret + 2 * sizeof(magic_t));
+		}
+	}
```
Comment (thomwiggers) [inline tests/test_kem.c:175]: Do we even still need `kem != NULL`?

File: tests/test_sig.c [hunk 2]
```diff
@@ -143,11 +143,19 @@ static OQS_STATUS sig_test_correctness(const char *method_name) {
 
 cleanup:
 	if (sig != NULL) {
-		OQS_MEM_secure_free(secret_key - sizeof(magic_t), sig->length_secret_key + 2 * sizeof(magic_t));
+		if (secret_key) {
+			OQS_MEM_secure_free(secret_key - sizeof(magic_t), sig->length_secret_key + 2 * sizeof(magic_t));
+		}
```
Comment (thomwiggers) [inline tests/test_sig.c:148]: do we still need `sig != NULL` here?

**Review by thomwiggers — CHANGES_REQUESTED** [review]
Looks pretty good, I just have one question about `sig` and `kem`. Are these pointers `NULL`-initialized?

**Comment by thomwiggers** [comment]
(Yes, they are `NULL`-initialized)

File: tests/test_sig.c (hunk 2 above)
Comment (baentsch) [reply tests/test_sig.c]: no

File: tests/test_kem.c (hunk 1 above)
Comment (baentsch) [reply tests/test_kem.c:173]: no

**Review by dstebila — APPROVED** [review]

**Comment by baentsch** [comment]
@thomwiggers Please re-review to remove the merge blocker.

**Review by thomwiggers — APPROVED** [review]
